name: CI-CD Pipeline

on:
  push:
    branches:
          - main
  workflow_dispatch:

jobs:
  test:
   runs-on: ubuntu-latest
   steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r flask-app/requirements.txt

      - name: Test
        working-directory: flask-app
        env:
          PYTHONPATH: .
        run: |
          pytest tests/
      - name: Build Docker image
        run: |
           docker build -t public-repo:${{github.sha}} ./flask-app

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with: 
         aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
         aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
         aws-region: us-east-1

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: PUSH to ECR Repo
        run: |
          docker tag public-repo:${{github.sha}} ${{steps.login-ecr.outputs.registry}}/public-repo:${{github.sha}}
          docker push ${{steps.login-ecr.outputs.registry}}/public-repo:${{github.sha}}

      - name: Deploy in EC2
        if: success()
        uses: appleboy/ssh-action@v1.2.2
        env:
          ECR_REGISTRY: ${{steps.login-ecr.outputs.registry}}
          IMAGE_TAG: ${{github.sha}}
        with:
          host: ${{secrets.EC2_HOST}}
          username : ec2-user
          key : ${{secrets.EC2_SSH_KEY}}
          envs: ECR_REGISTRY, IMAGE_TAG
          script: |
           set -e
           echo "Logging to ECR..."
           aws ecr get-login-password --region us-east-1 | \
           docker login --username AWS --password-stdin $ECR_REGISTRY/public-repo:$IMAGE_TAG

           echo "Pulling New Image"
           docker pull $ECR_REGISTRY/public-repo:$IMAGE_TAG

           echo "Stopping old container.."
           docker stop flask-app || true

           echo "removing old container "
           docker rm flask-app || true

           echo "Starting new Container  .."
           docker run -d --name flask-app -p 5000:5000 $ECR_REGISTRY/public-repo:$IMAGE_TAG

           echo "Waiting for application.."
           sleep 10

           echo "checking container.."
           docker ps --filter "name=flask-app"

           echo "Checking application health .."
           curl --fail http:/localhost:5000/health

           echo "Deployment successful .."

      - name: Send Success Email
        if: ${{success() }}
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: ${{secrets.SMTP_SERVER}}
          server_port : ${{secrets.SMTP_PORT}}
          username : ${{secrets.SMTP_USERNAME}}
          password : ${{secrets.SMTP_PASSWORD}}
          subject : "SUCCESS: CI/CD deployment -${{github.repository }}"
          to : ${{secrets.EMAIL_TO}}
          from : ${{secrets.EMAIL_FROM}}
          body : |  
            CI/CD PIPELINE SUCCESSFUL
          Repository : ${{github.repository}}
          Branch : ${{github.ref_name}}
          Commit SHA : ${{github.sha}}
          Docker Image : ${{secrets.ECR_REGISTRY}}/${{secrets.ECR_REPOSITORY}}:${{github.sha}}
          ECR : Image Successfully pushed
          EC2 Target : ${{secrets.EC2_HOST}}}
          Deployment Status : Application Successfully Deployed to EC2
          Pipeline Run : ${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}

      - name: Send Failure Email
        if: ${{failure()}}
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: ${{secrets.SMTP_SERVER}}
          server_port : ${{secrets.SMTP_PORT}}
          username : ${{secrets.SMTP_USERNAME}}
          password : ${{secrets.SMTP_PASSWORD}}
          subject : "FAILED : CI/CD deployment -${{github.repository }}"
          to : ${{secrets.EMAIL_TO}}
          from : ${{secrets.EMAIL_FROM}}
          body : |  
            CI/CD PIPELINE FAILED
            Repository : ${{github.repository}}
            Branch : ${{github.ref_name}}
            Commit SHA : ${{github.sha}}
            Failed Stage : Please Check the Test/Build/Deploy stage in pipelibe stage 
            Pipeline Run : ${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}   
          
           
          
          
       
        

           
           
           
      
        
         
